---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: subid-front-<BRANCH>
  name: subid-front-<BRANCH>
  namespace: sub-id
spec:
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: subid-front-<BRANCH>
  type: ClusterIP

---

  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: subid-front-<BRANCH>
    namespace: sub-id
    annotations:
      ingress.kubernetes.io/from-to-www-redirect: "true"
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      nginx.org/client-max-body-size: "10m"
      nginx.org/client-max-body-size: "10m"
      nginx.ingress.kubernetes.io/proxy-body-size: "10m"
      nginx.ingress.kubernetes.io/client-max-body-size: "10m"

  spec:
    ingressClassName: nginx
    rules:
      - host: <BRANCH>-subid.subsocial.network
        http:
          paths:
            - backend:
                service:
                  name: subid-front-<BRANCH>
                  port:
                    number: 3003
              path: "/"
              pathType: Prefix

    tls:
      - hosts:
        - <BRANCH>-subid.subsocial.network
        secretName: subsocial-ssl
